language: node_js
env:
  global:
  - GH_USER: nelson
node_js:
- '0.10'
install:
- npm install jshint mocha gulp bower -g
- npm install
- bower install
- gulp build
- mkdir out && cd $_
- git init
- git remote add origin $GH_REF
- cp -r ../dist/* .
- cp ../CNAME ./CNAME
- git add .
- git commit -m "Deployed to Github Pages"
- git push -f --quiet origin master:master
- cd ..
script: npm run-script deploy
